import { ImageResponse } from "next/og";

/**
 * Dynamic PNG app icons generated by Next.js's Metadata API.
 *
 * `generateImageMetadata` produces two distinct icon routes — a 192px
 * `/icon/small` (the spec-required smallest manifest icon) and a 512px
 * `/icon/large` (the manifest's launcher / splash size). Both are
 * referenced from `app/manifest.ts`.
 *
 * The artwork mirrors `app/icon.svg`: a deep aurora rounded-square base,
 * an amber/violet halo, and a luminous core. We render with absolute
 * pixel dimensions so the same JSX scales cleanly to both sizes — every
 * value is keyed off the `id` of the icon being requested.
 *
 * Note: ImageResponse runs in Next's Edge runtime; at build time it
 * rasterises the JSX to a PNG once, so subsequent requests are cached.
 */

export const contentType = "image/png";

interface IconVariant {
  id: string;
  size: { width: number; height: number };
}

const ICON_VARIANTS: readonly IconVariant[] = [
  { id: "small", size: { width: 192, height: 192 } },
  { id: "large", size: { width: 512, height: 512 } },
];

export function generateImageMetadata() {
  return ICON_VARIANTS.map((variant) => ({
    contentType,
    size: variant.size,
    id: variant.id,
  }));
}

export default function Icon({ id }: { id: string }) {
  const variant = ICON_VARIANTS.find((v) => v.id === id) ?? ICON_VARIANTS[0];
  const dimension = variant.size.width;
  const cornerRadius = Math.round(dimension * 0.21);
  const haloSize = Math.round(dimension * 0.92);
  const coreSize = Math.round(dimension * 0.42);
  const innerCoreSize = Math.round(dimension * 0.13);
  return new ImageResponse(
    <div
      style={{
        position: "relative",
        width: dimension,
        height: dimension,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        background: "linear-gradient(180deg, #0e0d18 0%, #08080d 100%)",
        borderRadius: cornerRadius,
        // Slight inner highlight to evoke the glassy chrome on the cover.
        boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.06)",
      }}
    >
      <div
        style={{
          position: "absolute",
          width: haloSize,
          height: haloSize,
          borderRadius: "50%",
          background:
            "radial-gradient(circle at 50% 50%, rgba(255, 206, 122, 0.78) 0%, " +
            "rgba(179, 144, 255, 0.45) 45%, rgba(10, 10, 15, 0) 100%)",
          display: "flex",
        }}
      />
      <div
        style={{
          position: "absolute",
          width: coreSize,
          height: coreSize,
          borderRadius: "50%",
          background:
            "radial-gradient(circle at 50% 50%, rgba(255, 245, 224, 0.95) 0%, " +
            "rgba(255, 183, 85, 0.72) 55%, rgba(122, 58, 0, 0) 100%)",
          display: "flex",
        }}
      />
      <div
        style={{
          position: "absolute",
          width: innerCoreSize,
          height: innerCoreSize,
          borderRadius: "50%",
          background: "rgba(255, 245, 224, 0.95)",
          display: "flex",
        }}
      />
    </div>,
    { ...variant.size }
  );
}
