import type { MetadataRoute } from "next";

/**
 * Lume web app manifest.
 *
 * Served at `/manifest.webmanifest` by Next.js's Metadata Route API.
 * Drives "Add to Home Screen" on iOS Safari and Android Chrome — once a
 * visitor installs Lume, launching from the home screen opens the app
 * standalone (no browser chrome) over a deep aurora background that
 * matches the in-app theme.
 *
 * Colors mirror the runtime theme defined in `app/globals.css`:
 *   - `theme_color`      → matches `viewport.themeColor` in `layout.tsx`
 *                          so the OS status bar / address bar tint stays
 *                          consistent with the in-app UI.
 *   - `background_color` → matches `--lu-base-deep`, the cover canvas
 *                          background, so the splash flash blends into
 *                          the cover.
 *
 * Icon coverage:
 *   - SVG (purpose: "any maskable")  — modern Android Chrome + desktop
 *     browsers prefer the vector source.
 *   - 192px / 512px PNGs              — generated by `app/icon.tsx`,
 *                                       required by the manifest spec
 *                                       and used by Android's "install"
 *                                       prompt and the OS launcher.
 *   - 180px PNG apple-touch-icon      — generated by `app/apple-icon.tsx`,
 *                                       picked up automatically by Next
 *                                       and emitted into the document
 *                                       head; included here as well for
 *                                       completeness.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Lume",
    short_name: "Lume",
    description:
      "A 23-specimen QR-scan light-form field guide across four floors.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#08080d",
    theme_color: "#0a0a0f",
    categories: ["entertainment", "education"],
    lang: "en",
    icons: [
      {
        src: "/icon.svg",
        type: "image/svg+xml",
        sizes: "any",
        purpose: "any",
      },
      {
        src: "/icon.svg",
        type: "image/svg+xml",
        sizes: "any",
        purpose: "maskable",
      },
      {
        src: "/icon/small",
        type: "image/png",
        sizes: "192x192",
        purpose: "any",
      },
      {
        src: "/icon/large",
        type: "image/png",
        sizes: "512x512",
        purpose: "any",
      },
      {
        src: "/apple-icon",
        type: "image/png",
        sizes: "180x180",
        purpose: "any",
      },
    ],
  };
}
