import {
  LUME_SPECIMENS,
  LUME_TOTAL_SPECIMENS,
  type LumeSpecimen,
} from "@lume/data/specimens";
import { LU } from "@lume/data/tokens";
import type { Metadata } from "next";
import { headers } from "next/headers";
import QRCode from "qrcode";
import type { CSSProperties } from "react";

/**
 * Dev / venue test-codes page — `/dev`.
 *
 * Renders all 23 specimens as scannable QR markers so the scanner can be
 * exercised on-screen (during development) or printed for venue dry-runs
 * before the real codes are produced. Each tile carries the specimen's
 * number, name, and slug so the QA checklist can correlate a scan to the
 * expected outcome.
 *
 * Each QR encodes the same `?c=<slug>` deep-link the production printed
 * markers will use — built off the request's resolved origin so the
 * payload is a fully-qualified URL (e.g. `https://lume.example/scan?c=lu-01-aurum`).
 * That keeps the page useful both when scanned by the same device
 * (Lume's own scanner consumes the URL via `extractQrSlug`) and by an
 * external phone scanning a printed copy.
 *
 * The route is a server component: QR SVGs are generated on the server
 * with `qrcode` and inlined directly into the response, so the page is
 * fully static after render and works without JS.
 *
 * The route is marked `noindex, nofollow` because it is internal QA, not
 * visitor-facing.
 */

export const metadata: Metadata = {
  title: "Lume — dev QR codes",
  description: "Internal QR test-codes page for venue and scanner QA.",
  robots: { index: false, follow: false },
};

/**
 * Resolve the request origin so the encoded QR URLs work both on the
 * device serving them and any other device pointed at the same host.
 * Falls back to a relative `/scan` path when forward-proxy headers are
 * unavailable — `extractQrSlug` accepts that form too.
 */
async function resolveOrigin(): Promise<string> {
  const h = await headers();
  const host = h.get("x-forwarded-host") ?? h.get("host");
  if (!host) {
    return "";
  }
  const proto = h.get("x-forwarded-proto") ?? "https";
  return `${proto}://${host}`;
}

/**
 * Build the `?c=<slug>` deep link for a specimen using the resolved
 * origin. When the origin is unknown we fall back to a relative
 * `/scan?c=...` path which `extractQrSlug` resolves correctly when the
 * QR is scanned by the same device that served the page.
 */
function buildDeepLink(origin: string, specimen: LumeSpecimen): string {
  const path = `/scan?c=${specimen.qr}`;
  return origin ? `${origin}${path}` : path;
}

/**
 * Render a single specimen QR + label tile. The SVG markup is generated
 * once on the server with `qrcode.toString` and dropped in via
 * `dangerouslySetInnerHTML` since the library returns a complete SVG
 * document.
 */
async function SpecimenTile({
  specimen,
  origin,
}: {
  specimen: LumeSpecimen;
  origin: string;
}) {
  const link = buildDeepLink(origin, specimen);
  const svg = await QRCode.toString(link, {
    type: "svg",
    errorCorrectionLevel: "M",
    margin: 1,
    color: {
      dark: "#0a0a0f",
      light: "#ffffff",
    },
  });
  const number = String(specimen.number).padStart(2, "0");
  return (
    <article style={TILE_STYLE}>
      <span style={TILE_NUMBER_STYLE}>NO. {number}</span>
      <div
        aria-label={`QR code for ${specimen.name.en} (${specimen.qr})`}
        // The string is generated by `qrcode.toString({ type: 'svg' })`
        // on the server, so the only "untrusted" inputs are our own slugs
        // and the resolved request origin (host header) — both of which
        // are validated before reaching this point.
        // biome-ignore lint/security/noDangerouslySetInnerHtml: server-rendered svg from a trusted lib
        dangerouslySetInnerHTML={{ __html: svg }}
        role="img"
        style={QR_BOX_STYLE}
      />
      <div style={TILE_NAME_STYLE}>{specimen.name.en}</div>
      <div style={TILE_META_STYLE}>{specimen.qr}</div>
      <div style={TILE_LINK_STYLE}>
        FLOOR {specimen.floor} · PLATE {specimen.plate}
      </div>
    </article>
  );
}

export default async function DevQrCodesPage() {
  const origin = await resolveOrigin();
  return (
    <main style={PAGE_STYLE}>
      <header style={HEADER_STYLE}>
        <p style={EYEBROW_STYLE}>Lume — internal QR codes</p>
        <h1 style={TITLE_STYLE}>{LUME_TOTAL_SPECIMENS} test markers</h1>
        <p style={INTRO_STYLE}>
          Scannable QR codes for every specimen, encoding the same{" "}
          <code style={CODE_STYLE}>?c=&lt;slug&gt;</code> deep-link the printed
          markers will carry. Use this page on-screen during development or
          print it for a venue dry-run.
        </p>
        <p style={INTRO_NOTE_STYLE}>
          Origin resolved as{" "}
          <strong style={ORIGIN_STYLE}>{origin || "(relative /scan)"}</strong>.
          Page is marked <code style={CODE_STYLE}>noindex, nofollow</code>.
        </p>
      </header>

      <section style={GRID_STYLE}>
        {LUME_SPECIMENS.map((specimen) => (
          <SpecimenTile key={specimen.qr} origin={origin} specimen={specimen} />
        ))}
      </section>
    </main>
  );
}

const PAGE_STYLE: CSSProperties = {
  minHeight: "var(--lu-screen-h)",
  background: LU.aurora.page,
  color: LU.base.ink,
  padding: "48px 0 64px",
};

const HEADER_STYLE: CSSProperties = {
  padding: "0 24px 24px",
  display: "flex",
  flexDirection: "column",
  gap: 8,
  maxWidth: 720,
};

const EYEBROW_STYLE: CSSProperties = {
  fontFamily: "var(--lu-font-mono)",
  fontSize: 12,
  letterSpacing: 2,
  textTransform: "uppercase",
  color: LU.base.ink2,
  margin: 0,
};

const TITLE_STYLE: CSSProperties = {
  fontSize: 32,
  fontWeight: 600,
  letterSpacing: -0.4,
  margin: 0,
};

const INTRO_STYLE: CSSProperties = {
  color: LU.base.ink2,
  margin: 0,
  fontSize: 14,
  lineHeight: 1.5,
};

const INTRO_NOTE_STYLE: CSSProperties = {
  color: LU.base.ink3,
  margin: 0,
  fontSize: 12,
  fontFamily: "var(--lu-font-mono)",
  letterSpacing: 0.5,
};

const ORIGIN_STYLE: CSSProperties = {
  color: LU.base.ink2,
  fontWeight: 500,
};

const CODE_STYLE: CSSProperties = {
  fontFamily: "var(--lu-font-mono)",
  background: LU.glass.surface1,
  padding: "1px 6px",
  borderRadius: 4,
  fontSize: 11,
};

const GRID_STYLE: CSSProperties = {
  padding: "0 24px",
  display: "grid",
  gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
  gap: 16,
};

const TILE_STYLE: CSSProperties = {
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  gap: 10,
  padding: "16px 12px",
  borderRadius: 18,
  border: `1px solid ${LU.rule.hair}`,
  background: LU.glass.surface1,
  textAlign: "center",
};

const TILE_NUMBER_STYLE: CSSProperties = {
  fontFamily: "var(--lu-font-mono)",
  fontSize: 11,
  letterSpacing: 2,
  textTransform: "uppercase",
  color: LU.base.ink3,
};

const QR_BOX_STYLE: CSSProperties = {
  width: 168,
  height: 168,
  background: "#ffffff",
  borderRadius: 8,
  padding: 8,
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  // Ensure the SVG fills the box without the qrcode lib's intrinsic size
  // taking over.
  boxSizing: "border-box",
};

const TILE_NAME_STYLE: CSSProperties = {
  fontSize: 15,
  fontWeight: 600,
  color: LU.base.ink,
  letterSpacing: 0.2,
};

const TILE_META_STYLE: CSSProperties = {
  fontFamily: "var(--lu-font-mono)",
  fontSize: 11,
  color: LU.base.ink2,
  letterSpacing: 1,
  textTransform: "lowercase",
};

const TILE_LINK_STYLE: CSSProperties = {
  fontFamily: "var(--lu-font-mono)",
  fontSize: 10,
  color: LU.base.ink3,
  letterSpacing: 1,
  textTransform: "uppercase",
};
