import {
  LUME_SPECIMENS,
  LUME_TOTAL_SPECIMENS,
  type LumeSpecimen,
} from "@lume/data/specimens";
import type { Metadata } from "next";
import { headers } from "next/headers";
import QRCode from "qrcode";

/**
 * Dev / venue test-codes page — `/dev`.
 *
 * Renders all 23 specimens as scannable QR markers so the scanner can be
 * exercised on-screen (during development) or printed for venue dry-runs
 * before the real codes are produced. Each tile carries the specimen's
 * number, name, and slug so the QA checklist can correlate a scan to the
 * expected outcome.
 *
 * Each QR encodes the same `?c=<slug>` deep-link the production printed
 * markers will use — built off the request's resolved origin so the
 * payload is a fully-qualified URL (e.g. `https://lume.example/scan?c=lu-01-aurum`).
 * That keeps the page useful both when scanned by the same device
 * (Lume's own scanner consumes the URL via `extractQrSlug`) and by an
 * external phone scanning a printed copy.
 *
 * The route is a server component: QR SVGs are generated on the server
 * with `qrcode` and inlined directly into the response, so the page is
 * fully static after render and works without JS.
 *
 * The route is marked `noindex, nofollow` because it is internal QA, not
 * visitor-facing.
 */

export const metadata: Metadata = {
  title: "Lume — dev QR codes",
  description: "Internal QR test-codes page for venue and scanner QA.",
  robots: { index: false, follow: false },
};

/**
 * Resolve the request origin so the encoded QR URLs work both on the
 * device serving them and any other device pointed at the same host.
 * Falls back to a relative `/scan` path when forward-proxy headers are
 * unavailable — `extractQrSlug` accepts that form too.
 */
async function resolveOrigin(): Promise<string> {
  const h = await headers();
  const host = h.get("x-forwarded-host") ?? h.get("host");
  if (!host) {
    return "";
  }
  const proto = h.get("x-forwarded-proto") ?? "https";
  return `${proto}://${host}`;
}

/**
 * Build the `?c=<slug>` deep link for a specimen using the resolved
 * origin. When the origin is unknown we fall back to a relative
 * `/scan?c=...` path which `extractQrSlug` resolves correctly when the
 * QR is scanned by the same device that served the page.
 */
function buildDeepLink(origin: string, specimen: LumeSpecimen): string {
  const path = `/scan?c=${specimen.qr}`;
  return origin ? `${origin}${path}` : path;
}

/**
 * Render a single specimen QR + label tile. The SVG markup is generated
 * once on the server with `qrcode.toString` and dropped in via
 * `dangerouslySetInnerHTML` since the library returns a complete SVG
 * document.
 */
async function SpecimenTile({
  specimen,
  origin,
}: {
  specimen: LumeSpecimen;
  origin: string;
}) {
  const link = buildDeepLink(origin, specimen);
  const svg = await QRCode.toString(link, {
    type: "svg",
    errorCorrectionLevel: "M",
    margin: 1,
    color: {
      dark: "#0a0a0f",
      light: "#ffffff",
    },
  });
  const number = String(specimen.number).padStart(2, "0");
  return (
    <article className="flex flex-col items-center gap-2.5 rounded-[18px] border border-rule-hair bg-glass-1 px-3 py-4 text-center">
      <span className="font-mono-lu text-[11px] text-ink-3 uppercase tracking-[2px]">
        NO. {number}
      </span>
      <div
        aria-label={`QR code for ${specimen.name.en} (${specimen.qr})`}
        className="flex h-[168px] w-[168px] items-center justify-center rounded-lg bg-white p-2"
        // The string is generated by `qrcode.toString({ type: 'svg' })`
        // on the server, so the only "untrusted" inputs are our own slugs
        // and the resolved request origin (host header) — both of which
        // are validated before reaching this point.
        // biome-ignore lint/security/noDangerouslySetInnerHtml: server-rendered svg from a trusted lib
        dangerouslySetInnerHTML={{ __html: svg }}
        role="img"
      />
      <div className="font-semibold text-[15px] text-ink tracking-[0.2px]">
        {specimen.name.en}
      </div>
      <div className="font-mono-lu text-[11px] text-ink-2 lowercase tracking-[1px]">
        {specimen.qr}
      </div>
      <div className="font-mono-lu text-[10px] text-ink-3 uppercase tracking-[1px]">
        FLOOR {specimen.floor} · PLATE {specimen.plate}
      </div>
    </article>
  );
}

export default async function DevQrCodesPage() {
  const origin = await resolveOrigin();
  return (
    <main className="min-h-[var(--lu-screen-h)] bg-aurora-page pt-12 pb-16 text-ink">
      <header className="flex max-w-[720px] flex-col gap-2 px-6 pb-6">
        <p className="m-0 font-mono-lu text-ink-2 text-xs uppercase tracking-[2px]">
          Lume — internal QR codes
        </p>
        <h1 className="m-0 font-semibold text-[32px] tracking-[-0.4px]">
          {LUME_TOTAL_SPECIMENS} test markers
        </h1>
        <p className="m-0 text-ink-2 text-sm leading-normal">
          Scannable QR codes for every specimen, encoding the same{" "}
          <code className="rounded-[4px] bg-glass-1 px-1.5 py-[1px] font-mono-lu text-[11px]">
            ?c=&lt;slug&gt;
          </code>{" "}
          deep-link the printed markers will carry. Use this page on-screen
          during development or print it for a venue dry-run.
        </p>
        <p className="m-0 font-mono-lu text-ink-3 text-xs tracking-[0.5px]">
          Origin resolved as{" "}
          <strong className="font-medium text-ink-2">
            {origin || "(relative /scan)"}
          </strong>
          . Page is marked{" "}
          <code className="rounded-[4px] bg-glass-1 px-1.5 py-[1px] font-mono-lu text-[11px]">
            noindex, nofollow
          </code>
          .
        </p>
      </header>

      <section className="grid grid-cols-[repeat(auto-fill,minmax(220px,1fr))] gap-4 px-6">
        {LUME_SPECIMENS.map((specimen) => (
          <SpecimenTile key={specimen.qr} origin={origin} specimen={specimen} />
        ))}
      </section>
    </main>
  );
}
