import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const LOCALES = ["en", "zh-tw", "zh-cn", "ja", "ko"] as const;
const DEFAULT_CSV_URL_ENV = "LUME_CONTENT_CSV_URL";
const DEFAULT_OUTPUT_PATH = resolve(
  import.meta.dir,
  "../../../packages/data/src/specimen-content.generated.ts"
);
const HTTP_URL_PATTERN = /^https?:\/\//;

type Locale = (typeof LOCALES)[number];
type LocalizedText = Readonly<Record<Locale, string>>;

export interface SpecimenContentRow {
  readonly name: LocalizedText;
  readonly notes: LocalizedText;
  readonly qr: string;
}

export interface ExpectedSpecimenIdentity {
  readonly number: number;
  readonly qr: string;
}

interface SyncContentOptions {
  readonly csvUrl?: string;
  readonly outputPath?: string;
}

const REQUIRED_COLUMNS = [
  "qr",
  ...LOCALES.flatMap((locale) => [`name_${locale}`, `notes_${locale}`]),
] as const;

export function parseSpecimenContentCsv(csv: string): SpecimenContentRow[] {
  const records = parseCsvRecords(csv);
  const [header, ...body] = records.filter((record) =>
    record.some((cell) => cell.trim().length > 0)
  );

  if (!header) {
    throw new Error("Content CSV is empty.");
  }

  const columnIndexes = new Map<string, number>();
  header.forEach((column, index) => {
    columnIndexes.set(column.trim(), index);
  });

  const missingColumns = REQUIRED_COLUMNS.filter(
    (column) => !columnIndexes.has(column)
  );
  if (missingColumns.length > 0) {
    throw new Error(
      `Content CSV is missing columns: ${missingColumns.join(", ")}`
    );
  }

  return body.map((record) => {
    const cell = (column: string) =>
      record[columnIndexes.get(column) ?? -1] ?? "";
    const name = Object.fromEntries(
      LOCALES.map((locale) => [locale, cell(`name_${locale}`).trim()])
    ) as Record<Locale, string>;
    const notes = Object.fromEntries(
      LOCALES.map((locale) => [locale, cell(`notes_${locale}`).trim()])
    ) as Record<Locale, string>;

    return {
      qr: cell("qr").trim(),
      name,
      notes,
    };
  });
}

export function validateSpecimenContentRows(
  rows: readonly SpecimenContentRow[],
  expectedSpecimens: readonly ExpectedSpecimenIdentity[]
): void {
  const errors: string[] = [];
  const expectedSlugs = new Set(
    expectedSpecimens.map((specimen) => specimen.qr)
  );
  const seenSlugs = new Set<string>();

  rows.forEach((row, index) => {
    const rowLabel = row.qr || `row ${index + 2}`;

    if (!row.qr) {
      errors.push(`${rowLabel}: missing qr`);
      return;
    }

    if (!expectedSlugs.has(row.qr)) {
      errors.push(`unknown qr ${row.qr}`);
    }

    if (seenSlugs.has(row.qr)) {
      errors.push(`duplicate row for ${row.qr}`);
    }
    seenSlugs.add(row.qr);

    for (const locale of LOCALES) {
      if (!row.name[locale]) {
        errors.push(`${rowLabel}: missing name_${locale}`);
      }
      if (!row.notes[locale]) {
        errors.push(`${rowLabel}: missing notes_${locale}`);
      }
    }
  });

  for (const specimen of expectedSpecimens) {
    if (!seenSlugs.has(specimen.qr)) {
      errors.push(`missing row for ${specimen.qr}`);
    }
  }

  if (errors.length > 0) {
    throw new Error(`Content CSV validation failed:\n- ${errors.join("\n- ")}`);
  }
}

export function buildSpecimenContentModule(
  rows: readonly SpecimenContentRow[],
  expectedSpecimens: readonly ExpectedSpecimenIdentity[]
): string {
  validateSpecimenContentRows(rows, expectedSpecimens);

  const rowsBySlug = new Map(rows.map((row) => [row.qr, row]));
  const entries = expectedSpecimens.map((specimen) => {
    const row = rowsBySlug.get(specimen.qr);
    if (!row) {
      throw new Error(`missing row for ${specimen.qr}`);
    }
    return `  ${JSON.stringify(specimen.qr)}: ${formatContentRow(row)},`;
  });

  return `// Generated by \`bun run sync-content\`. Do not edit by hand.\n// Source columns: ${REQUIRED_COLUMNS.join(", ")}\n\nimport type { LumeSpecimenName } from "./specimens";\n\ntype LumeSpecimenContent = Readonly<{\n  name: LumeSpecimenName;\n  notes: LumeSpecimenName;\n}>;\n\nexport const LUME_SPECIMEN_CONTENT: Readonly<Record<string, LumeSpecimenContent>> = {\n${entries.join("\n")}\n} as const;\n`;
}

export async function syncSpecimenContent(
  expectedSpecimens: readonly ExpectedSpecimenIdentity[],
  options: SyncContentOptions = {}
): Promise<{ outputPath: string; rowCount: number }> {
  const csvUrl = options.csvUrl ?? process.env[DEFAULT_CSV_URL_ENV];
  if (!csvUrl) {
    throw new Error(
      `Missing CSV URL. Pass --url <published-csv-url> or set ${DEFAULT_CSV_URL_ENV}.`
    );
  }

  const csv = await readCsvSource(csvUrl);
  const rows = parseSpecimenContentCsv(csv);
  const generated = buildSpecimenContentModule(rows, expectedSpecimens);
  const outputPath = resolve(options.outputPath ?? DEFAULT_OUTPUT_PATH);

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, generated);

  return { outputPath, rowCount: rows.length };
}

export async function runSyncContentCommand(
  expectedSpecimens: readonly ExpectedSpecimenIdentity[],
  argv: readonly string[] = process.argv.slice(2)
): Promise<void> {
  const options = parseArgs(argv);
  const result = await syncSpecimenContent(expectedSpecimens, options);
  console.log(
    `Synced ${result.rowCount} specimen rows to ${result.outputPath}`
  );
}

function parseArgs(argv: readonly string[]): SyncContentOptions {
  const options: { csvUrl?: string; outputPath?: string } = {};

  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "sync-content") {
      continue;
    }
    if (arg === "--url") {
      options.csvUrl = requireValue(argv, index, arg);
      index += 1;
      continue;
    }
    if (arg.startsWith("--url=")) {
      options.csvUrl = arg.slice("--url=".length);
      continue;
    }
    if (arg === "--output") {
      options.outputPath = requireValue(argv, index, arg);
      index += 1;
      continue;
    }
    if (arg.startsWith("--output=")) {
      options.outputPath = arg.slice("--output=".length);
      continue;
    }
    throw new Error(`Unknown sync-content argument: ${arg}`);
  }

  return options;
}

function requireValue(
  argv: readonly string[],
  index: number,
  flag: string
): string {
  const value = argv[index + 1];
  if (!value) {
    throw new Error(`${flag} requires a value.`);
  }
  return value;
}

async function readCsvSource(csvUrl: string): Promise<string> {
  if (csvUrl.startsWith("file://")) {
    return Bun.file(new URL(csvUrl)).text();
  }

  if (!HTTP_URL_PATTERN.test(csvUrl)) {
    return Bun.file(csvUrl).text();
  }

  const response = await fetch(csvUrl);
  if (!response.ok) {
    throw new Error(
      `Failed to fetch content CSV (${response.status} ${response.statusText}) from ${csvUrl}`
    );
  }
  return response.text();
}

// biome-ignore lint/complexity/noExcessiveCognitiveComplexity: CSV quoting/newline state machine is clearer kept in one pass.
function parseCsvRecords(csv: string): string[][] {
  const records: string[][] = [];
  let record: string[] = [];
  let field = "";
  let inQuotes = false;
  const pushField = () => {
    record.push(field);
    field = "";
  };
  const pushRecord = () => {
    pushField();
    records.push(record);
    record = [];
  };

  for (let index = 0; index < csv.length; index += 1) {
    const char = csv[index];
    const next = csv[index + 1];

    if (inQuotes) {
      if (char === '"' && next === '"') {
        field += '"';
        index += 1;
        continue;
      }
      if (char === '"') {
        inQuotes = false;
        continue;
      }
      field += char;
      continue;
    }

    if (char === '"') {
      inQuotes = true;
      continue;
    }
    if (char === ",") {
      pushField();
      continue;
    }
    if (char === "\n") {
      pushRecord();
      continue;
    }
    if (char === "\r") {
      continue;
    }
    field += char;
  }

  if (inQuotes) {
    throw new Error("Content CSV has an unterminated quoted cell.");
  }

  if (field.length > 0 || record.length > 0) {
    pushField();
    records.push(record);
  }

  return records;
}

function formatContentRow(row: SpecimenContentRow): string {
  return `{ name: ${formatLocalized(row.name)}, notes: ${formatLocalized(row.notes)} }`;
}

function formatLocalized(value: LocalizedText): string {
  const fields = LOCALES.map(
    (locale) => `${JSON.stringify(locale)}: ${JSON.stringify(value[locale])}`
  );
  return `{ ${fields.join(", ")} }`;
}
